### PR TITLE
Updated likelihood with automatic caching

### PR DESCRIPTION
**Pull request by jellis18**
Of course I need some tests but this is pretty awesome. Almost everything is cached from the individual `Signal` level to the `PTA` level. In terms of the API nothing has really changed but the internals have changed a decent amount.

I can't push directly to your PR so I'm doing it this way.

### CODE REVIEW

**Comment by vallis** [comment]
Thanks Justin. Given you're enthusiasm, I'm very excited to see this!

M

**Comment by jellis18** [comment]
One thing I think we may want to change is to have the likelihood code sit above the signals directory. This isn't important for functionality so maybe we can just wait until a bit later since there will need to be some other re-arrangements

**Comment by jellis18** [comment]
OK we are almost ready to merge. The likelihood is working and has tests both with and without spatial correlations. All of the caching is there and the likelihood evaluation is as good as `PAL2`. The only thing I want to do before merging is to change the way the likelihood is initialized. I'd like some way to tell it what `phiinv` method to use.

**Comment by jellis18** [comment]
Actually we may also want `CommonBasisGP` signals to not require an ORF. If it doesn't find one it doesn't do the common signal part. Right now for common signals without spatial correlations I have just been using the regular signal with pre-initialized parameters.

**Comment by jellis18** [comment]
OK, I've added  a keyword argument to the likelihood so that we can set the phiinv method there like
`pta.get_lnlikelihood(xs, phiinv_method='sparse')`. The default is set to 'partition'

Can you go ahead and merge this now so that we can merge it into the master enterprise branch?

**Pull request merged**
